# Author : Krishnendu De
# Co-Author: Claude Fable 5.0
"""Log parsers. Each module exposes `parse(content: str) -> Iterator[NormalizedEvent]`."""
from __future__ import annotations

from . import (aws_cloudtrail, aws_guardduty, aws_securityhub, azure_activity, cef,
               cisco_asa, cisco_ftd, cisco_ios, crowdstrike_csv, crowdstrike_json,
               defender_xdr, entra_signin, fortinet_fortigate, gcp_audit, generic_json,
               generic_syslog, github_audit, gitlab_audit, leef, linux_auditd,
               m365_audit, meraki, netflow, nutanix_files, nutanix_pc,
               okta_system_log, paloalto_csv, paloalto_syslog, qualys, rapid7,
               suricata_eve, sysmon, tenable, web_access, windows_security,
               zeek_json, zeek_tsv)

# Format key -> parser module. Keys are also the values of the UI "format" dropdown.
PARSERS = {
    "paloalto_csv": paloalto_csv,
    "paloalto_syslog": paloalto_syslog,
    "crowdstrike_csv": crowdstrike_csv,
    "crowdstrike_json": crowdstrike_json,
    "fortinet_fortigate": fortinet_fortigate,
    "windows_security": windows_security,
    "sysmon": sysmon,
    "linux_auditd": linux_auditd,
    "web_access": web_access,
    "suricata_eve": suricata_eve,
    "cef": cef,
    "leef": leef,
    "cisco_asa": cisco_asa,
    "cisco_ftd": cisco_ftd,
    "zeek_tsv": zeek_tsv,
    "generic_syslog": generic_syslog,
    "aws_cloudtrail": aws_cloudtrail,
    "aws_guardduty": aws_guardduty,
    "aws_securityhub": aws_securityhub,
    "defender_xdr": defender_xdr,
    "netflow": netflow,
    "qualys": qualys,
    "tenable": tenable,
    "rapid7": rapid7,
    "m365_audit": m365_audit,
    "okta_system_log": okta_system_log,
    "entra_signin": entra_signin,
    "cisco_ios": cisco_ios,
    "meraki": meraki,
    "nutanix_pc": nutanix_pc,
    "nutanix_files": nutanix_files,
    "zeek_json": zeek_json,
    "gcp_audit": gcp_audit,
    "azure_activity": azure_activity,
    "github_audit": github_audit,
    "gitlab_audit": gitlab_audit,
    "generic_json": generic_json,
}

FORMAT_LABELS = {
    "paloalto_csv": "Palo Alto NGFW — CSV export",
    "paloalto_syslog": "Palo Alto NGFW — syslog",
    "crowdstrike_csv": "CrowdStrike Falcon — CSV export",
    "crowdstrike_json": "CrowdStrike Falcon — JSON",
    "fortinet_fortigate": "Fortinet FortiGate — syslog (key=value)",
    "windows_security": "Windows Security Event Log — CSV / JSON",
    "sysmon": "Microsoft Sysmon — Operational log (JSON / CSV)",
    "linux_auditd": "Linux auditd — audit.log",
    "web_access": "Apache / Nginx — access log (CLF / combined)",
    "suricata_eve": "Suricata — EVE JSON",
    "cef": "CEF — Common Event Format (generic)",
    "leef": "LEEF — Log Event Extended Format (Tripwire Log Center / QRadar; generic)",
    # ASA and FTD split by GRAMMAR, not by product: cisco_asa owns the Lina
    # data-plane free text (%ASA-6-302013 …), cisco_ftd the unified security
    # events (430001-430005) and the FMC/Snort SFIMS alert.
    "cisco_asa": "Cisco ASA / FTD — Lina syslog",
    "cisco_ftd": "Cisco Firepower Threat Defense — security events (430001-430005 / SFIMS)",
    "zeek_tsv": "Zeek (Bro) — TSV (conn / dns / http …)",
    "generic_syslog": "Generic syslog — RFC 3164 / 5424",
    "aws_cloudtrail": "AWS CloudTrail — JSON",
    "aws_guardduty": "AWS GuardDuty — findings (JSON)",
    "aws_securityhub": "AWS Security Hub — findings (ASFF JSON)",
    "defender_xdr": "Microsoft Defender XDR — alerts / incidents (Graph)",
    "netflow": "NetFlow v5/v9/IPFIX — decoded flows",
    "qualys": "Qualys VMDR — Host List Detection (XML)",
    "tenable": "Tenable Vulnerability Management — vulns export (JSON)",
    "rapid7": "Rapid7 InsightVM — asset/finding/vulnerability (JSON)",
    "m365_audit": "Microsoft 365 — Unified Audit Log",
    "okta_system_log": "Okta — System Log",
    "entra_signin": "Microsoft Entra ID — sign-in logs",
    "cisco_ios": "Cisco IOS / IOS-XE / NX-OS — syslog",
    "meraki": "Cisco Meraki — syslog",
    "nutanix_pc": "Nutanix Prism Central — audit / API / Flow (syslog)",
    "nutanix_files": "Nutanix Files / Data Lens — file audit (JSON / syslog)",
    "zeek_json": "Zeek (Bro) — JSON (conn / dns / http …)",
    "gcp_audit": "Google Cloud — Cloud Audit Logs",
    "azure_activity": "Microsoft Azure — Activity Log",
    "github_audit": "GitHub — audit log",
    "gitlab_audit": "GitLab — audit events",
    "generic_json": "Generic JSON / NDJSON (catch-all)",
}
